version: '3.7'
services:
  gocv:
    build:
      context: .
    working_dir: /go/src/github.com/tomnlittle/gocv-server
    command: /go/bin/gocv-server -cache
    environment:
      - AWS_REGION
      - AWS_PROFILE
    volumes:
      - .:/go/src/github.com/tomnlittle/gocv-server
      - ~/.aws:/root/.aws
    ports:
      - 8000:8000

  memcache:
    image: bitnami/memcached
    environment:
      - MEMCACHED_CACHE_SIZE=512
